plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
github:
  is_project_page: false
include:
  - privacypolicy.md
theme: jekyll-theme-slate
name: DO OR DIE Privacy Policy